### ISSUE TITLE
 The number of CSV files does not match the expected number of combinations based on the provided parameters 

### ISSUE THREAD

**Issue by Kounavis** [altzbox/Chopper-tuning-guide#6]
The number of CSV files (1172) does not match the expected number of combinations based on the provided parameters (1232).

**Comment by altzbox** [comment]
If you launch macro with default parameters, it must be 1232 combinations.
Check your Pi. Free disc space, etc.

**Comment by Kounavis** [comment]
You were right. I didn't have enough disk space.
